[build]
  publish = "dist/public"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[functions]
  directory = "api"
  external_node_modules = ["@babel/preset-typescript", "lightningcss"]

[dev]
  command = "npm run dev"
  port = 3000
  publish = "dist/public"
